### ISSUE TITLE
use snake case for variable's names

### ISSUE THREAD

**Issue by klim0v** [introphin/proto-stat-view#1]
OMG! Use CamelCase (with an initial capital) for message names – for example, SongServerRequest. Use underscore_separated_names for field names – for example, song_name. 
And you can reed more https://developers.google.com/protocol-buffers/docs/style

**Comment by lyashm** [comment]
> OMG! Use CamelCase (with an initial capital) for message names – for example, SongServerRequest. Use underscore_separated_names for field names – for example, song_name.
> And you can reed more https://developers.google.com/protocol-buffers/docs/style

Close its shit, please!

**Comment by klim0v** [comment]
Сonsider this in the future!

**Comment by klim0v** [comment]
consider this in the future

**Comment by m-lyashenko** [comment]
You'll write here again.. I'll write you ban on Google

**Comment by lyashm** [comment]
> consider this in the future

You'll write here again.. I'll write you ban on Google

**Comment by yaaitor** [comment]
Vash inglish is bad, owful =(

**Comment by yaaitor** [comment]
both of you

**Comment by lyashm** [comment]
> Vash inglish is bad, owful =(

What you write - NONSENSE! Do you even understand how slice works?

**Comment by klim0v** [comment]
thank
